FROM node:21-alpine

ARG REACT_PORT

WORKDIR /frontend
COPY frontend/package*.json /frontend
RUN npm install
RUN npm install styled-components
RUN npm install axios
COPY frontend/. /frontend
RUN npm run build
ENV PORT=${REACT_PORT}
ENV REACT_APP_SERVER_URL=http://localhost:${NGINX_PORT}
ENV HOST=0.0.0.0
EXPOSE ${REACT_PORT}
CMD ["npm", "start"]